name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on changes to main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Replace placeholders in config file
        env:
          DEBUG_MODE: "true"
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          if [ -z "$SNOWFLAKE_PASSWORD" ]; then
            echo "Error: SNOWFLAKE_PASSWORD is not set!"
            exit 1
          fi
            export SNOWFLAKE_PASSWORD="${{ secrets.SNOWFLAKE_PASSWORD }}"
            sed -i "s/\${SNOWFLAKE_PASSWORD}/$SNOWFLAKE_PASSWORD/g" toolkit.conf

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust based on your needs

      - name: Download Toolkit CLI
        run: |
          curl -fO https://repo.phdata.io/TpxWxi1R49dA9VqJ/toolkit-cli/maven/io/phdata/toolkit/toolkit-cli/0.60.0/toolkit-cli-0.60.0.zip

      - name: Extract Toolkit CLI
        run: |
          unzip toolkit-cli-0.60.0.zip -d ./
          mv toolkit-cli-0.60.0/* .

      - name: Toolkit Authorization
        run: |
          export TOOLKIT_AUTH_TOKEN="${{ secrets.TOOLKIT_AUTH_TOKEN }}"
          export SNOWFLAKE_PASSWORD="${{ secrets.SNOWFLAKE_PASSWORD }}"
          sed -i "s/\${SNOWFLAKE_PASSWORD}/$SNOWFLAKE_PASSWORD/g" toolkit.conf
          ./toolkit init
          ./toolkit auth

      - name: Run Toolkit Provision
        run: |
          export TOOLKIT_AUTH_TOKEN="${{ secrets.TOOLKIT_AUTH_TOKEN }}"
          export SNOWFLAKE_PASSWORD="${{ secrets.SNOWFLAKE_PASSWORD }}"
          sed -i "s/\${SNOWFLAKE_PASSWORD}/$SNOWFLAKE_PASSWORD/g" toolkit.conf
          ./toolkit auth 
          ./toolkit provision apply --plan
          ./toolkit provision apply 

